// Builds src/generated/art-inline.ts for the single-file build: every image in public/art,
// downscaled with macOS `sips` and embedded as a data URI, so the published artifact carries
// its own art. Run with --clear to reset the module to an empty map (the normal build uses
// the files in public/art by URL instead).
//
//   tsx scripts/inline-art.ts          # generate (used by pnpm build:single)
//   tsx scripts/inline-art.ts --clear  # reset

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'

const OUT = 'src/generated/art-inline.ts'
const SRC = 'public/art'
const TMP = '.art-tmp'

function write(map: Record<string, string>) {
  mkdirSync('src/generated', { recursive: true })
  const body = Object.entries(map)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n')
  writeFileSync(OUT, `// Generated by scripts/inline-art.ts. Empty in dev; filled for the single-file build.\nexport const ART_INLINE: Record<string, string> = {\n${body}\n}\n`)
}

if (process.argv.includes('--clear')) {
  write({})
  console.log('art-inline cleared')
  process.exit(0)
}

if (!existsSync(SRC)) {
  write({})
  console.log('no public/art; wrote empty map')
  process.exit(0)
}

// Max edge per kind. Cards show at most ~190px wide, so 480 is plenty at 2x.
const maxEdge = (id: string) => (id === 'title' ? 1024 : id === 'card-back' ? 360 : id === 'table' ? 512 : 480)
const quality = (id: string) => (id === 'title' ? 68 : 72)

rmSync(TMP, { recursive: true, force: true })
mkdirSync(TMP)
const map: Record<string, string> = {}
let total = 0
for (const f of readdirSync(SRC).sort()) {
  if (!/\.(jpe?g|png|webp)$/i.test(f)) continue
  const id = f.replace(/\.[^.]+$/, '')
  const out = join(TMP, `${id}.jpg`)
  execFileSync('sips', ['-s', 'format', 'jpeg', '-s', 'formatOptions', String(quality(id)), '-Z', String(maxEdge(id)), join(SRC, f), '--out', out], { stdio: 'ignore' })
  const buf = readFileSync(out)
  total += buf.length
  map[id] = `data:image/jpeg;base64,${buf.toString('base64')}`
}
// The UI kit: transparent PNG overlays, kept as PNG and only downscaled.
const UI = join(SRC, 'ui')
if (existsSync(UI)) {
  for (const f of readdirSync(UI).sort()) {
    if (!/\.png$/i.test(f)) continue
    const id = f.replace(/\.[^.]+$/, '')
    const out = join(TMP, `ui-${id}.png`)
    execFileSync('sips', ['-Z', '640', join(UI, f), '--out', out], { stdio: 'ignore' })
    const buf = readFileSync(out)
    total += buf.length
    map[`ui/${id}`] = `data:image/png;base64,${buf.toString('base64')}`
  }
}
rmSync(TMP, { recursive: true, force: true })
write(map)
console.log(`inlined ${Object.keys(map).length} images, ${(total / 1024 / 1024).toFixed(2)} MB of jpeg before base64`)
